import { cn } from '@/lib/utils';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NavBar } from '@/components/navbar/NavBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        'bg-gradient-to-br from-[#17A1BA] to-[#00AEEF] text-white',
        inter.className
        )}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
